### ISSUE TITLE
Fails to add a trailing newline to files without one

### ISSUE THREAD

**Issue by raphinesse** [perry-mitchell/add-newlines#1]

**Comment by perry-mitchell** [comment]
Could you please describe the problem a bit better? I can't do much with this.

What type of file, OS, new line type in the file etc..

**Comment by raphinesse** [comment]
IMHO, it should not depend on any of the factors you asked for. 
But for completeness sake: XML file, Linux, Unix.

I expected this program to add a trailing `\n` to files that do not already end in one. 
Suppose you have an XML file that ends in `>`. This program will then fail to append any newline to the file since the regex `/(\r\n|\n)+$/` [used for the replacing](https://github.com/perry-mitchell/add-newlines/blob/3fdba9143215b2fea350a5de38369fb1cd5691d2/source/index.js) of course won't match `>`. I suggest changing the regex to `/(\r\n|\n)*$/`.

**Comment by perry-mitchell** [comment]
Thanks for posting @raphinesse - this is definitely an issue.

It's generally considered helpful to leave some kind of description, even if it's obvious what the issue is.

**Comment by raphinesse** [comment]
Yeah, I know. But then again I try to minimize the time I spend by writing issues :wink:

**Comment by perry-mitchell** [comment]
Fixed in 0.2.0.
